--Q1. What is the total revenue generated by male vs. female customers?

SELECT GENDER,SUM(PURCHASE_AMOUNT) AS REVENUE
FROM CUSTOMER
GROUP BY GENDER;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT CUSTOMER_ID,PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED = 'Yes' AND PURCHASE_AMOUNT >= (SELECT AVG(PURCHASE_AMOUNT) FROM  CUSTOMER)

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT ITEM_PURCHASED,ROUND(AVG(REVIEW_RATING)::NUMERIC,2)AS AVERAGE_PRODUCT_RATING
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY AVG(REVIEW_RATING) DESC
LIMIT 5 ;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT SHIPPING_TYPE,
ROUND(AVG(PURCHASE_AMOUNT),2) AS AVERAGE_PURCHASE_AMOUNT
FROM CUSTOMER
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY SHIPPING_TYPE;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT SUBSCRIPTION_STATUS,
COUNT(CUSTOMER_iD) AS TOTAL_CUSTOMER,
ROUND(AVG(PURCHASE_AMOUNT),2) AS AVERAGE_SPEND,
ROUND(SUM(PURCHASE_AMOUNT),2) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY TOTAL_REVENUE,AVERAGE_SPEND;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT ITEM_PURCHASED,
ROUND(100 * SUM(CASE WHEN DISCOUNT_APPLIED = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS DISCOUNT_RATE
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH CUSTOMER_TYPE AS(
SELECT CUSTOMER_ID,PREVIOUS_PURCHASES,
CASE 
     WHEN PREVIOUS_PURCHASES = 1 THEN 'NEW'
	 WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'RETURNING'
	 ELSE 'LOYAL'
	 END AS CUSTOMER_SEGMENT
FROM CUSTOMER
)
SELECT CUSTOMER_SEGMENT,COUNT(*) AS "NUMBER OF CUSTOMERS"
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT;

--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
count(customer_id) as repeated_customers
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 

select age_group,
sum(purchase_amount) as total_revenve
from customer
group by age_group
order by sum(purchase_amount) desc;


select * from customer;
